export * from "./Wrapper/Wrapper"; 
export * from "./Card/Card";
export * from "./MovieList/MovieList";
export * from "./SearchBar/SearchBar";
export * from "./Loader/Loader";
export * from "./Header/Header"
export * from "./BestMovies/BestMovies";
export * from "./ChangePage/ChangePage";
export * from "./ButtonNav"